#Valid for kubectl 1.9.6 & kubernetes 1.9.6
#Very flaky default api-Versioning provided. Take extreme caution while changing api-Version fields, or upgrading kubernetes version.
#Deployment takes some time to properly deploy and connect all components with each other. Have some patience while staging.
#Always opening the port 80, or 8080 externally due to issues revolving exposing port on loadBalancer(Both cloudflare and GCP)


# Creating service for frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend                    #selection of service by label
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000                #the port on the concerned cluster pods that needs to be attached to service
  type: NodePort                      #Requirements for ingress

---

#Deploying frontend on kubernetes cluster
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1 # tells deployment to run no. of pods matching the template
  selector:
    matchLabels:
      app: frontend
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: frontend          #labels for service selector to work properly
    spec:
      containers:
      - name: frontend
        image: gcr.io/consert-171718/bitbucket-prateekrastogi-frontend:production
        ports:
        - containerPort: 3000    #opens port for the other pods of kubernetes cluster
        imagePullPolicy: Always

---

#Horizontal Pod Scaling of frontend Deployment
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

---

# Creating service for backend
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend                    #selection of service by label
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 3100                #the port on the concerned cluster pods that needs to be attached to service
  type: NodePort

---

# Creating separate backend websocket service for ingress as ingress cann't take same service for two different forwarding rules
apiVersion: v1
kind: Service
metadata:
  name: backend-ws
spec:
  selector:
    app: backend                    #selection of service by label
  ports:
    - name: http
      protocol: "TCP"
      port: 80
      targetPort: 5000                #the port on the concerned cluster pods that needs to be attached to service
  type: NodePort

---

#Deploying backend on kubernetes cluster
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 #tells deployment to run no. of pods matching the template
  selector:
    matchLabels:
      app: backend  
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: backend          #labels for service selector to work properly
    spec:
      containers:
      - name: backend
        image: gcr.io/consert-171718/bitbucket-prateekrastogi-backend:production
        ports:
        - containerPort: 3100    #opens port for the other pods of kubernetes cluster
          name: http
        - containerPort: 5000
          name: ws
        imagePullPolicy: Always  

---

#Horizontal Pod Scaling of backend Deployment
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

---

# Creating service for seeder
apiVersion: v1
kind: Service
metadata:
  name: seeder
spec:
  selector:
    app: seeder                    #selection of service by label
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3200             #The port on the concerned cluster pods that needs to be attached to service
  type: NodePort

---

#Deploying seeder on kubernetes cluster
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: seeder-deployment
spec:
  replicas: 1 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: seeder
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: seeder          #labels for service selector to work properly
    spec:
      containers:
      - name: seeder
        image: gcr.io/consert-171718/bitbucket-prateekrastogi-seeder:production
        ports:
        - containerPort: 3200    #opens port for the other pods of kubernetes cluster
        imagePullPolicy: Always

---

#Horizontal Pod Scaling of seeder Deployment
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: seeder
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: seeder
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80