apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 443
    targetPort: 9200                     #the port on the concerned cluster pods that needs to be attached to service
    protocol: TCP
  loadBalancerIP: 104.198.252.222
  type: LoadBalancer