apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  selector:
    component: elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200                     #the port on the concerned cluster pods that needs to be attached to service
    protocol: TCP                        #due to failure to install x-pack required for authentication
  clusterIP: 10.55.250.250               #allocating a clusterip coz the service discovery by name is not working inside the cluster for some weird bug, so hardcoding the clusterIp in the code to access elastic search