apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consert-ingress
spec:
  tls:
  - hosts:
    - consert.live
    secretName: consert-secret
  rules:
  - host: consert.live
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 3000

