# Choosing either port 80 or 8080 as service port due to gcp L7 loadBalancer limitations. It can only work on 80 or 8080
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: consert-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: consert
spec:
  tls:
  - hosts:
    - consert.live
    secretName: consert-secret
  rules:
  - host: consert.live
    http:
      paths:
      - path:
        backend:
          serviceName: frontend
          servicePort: 80
  - host: accounts.consert.live
    http:
      paths:
      - path:
        backend:
          serviceName: backend
          servicePort: 80
  - host: accounts.consert.live
    http:
      paths:
      - path:
        backend:
          serviceName: backend
          servicePort: 8080
  - host: seeder.consert.live
    http:
      paths:
      - path:
        backend:
          serviceName: seeder
          servicePort: 80
