# MongoDb StatefulSet Deployment
# Creating StorageClass for mongodb
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: mongodb
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

---

#Creating Mongo Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  selector:
    role: mongo
  ports:
  - port: 27017                           #Mongo protocol not supported on cloudflare. Thus, no dns. so just using the gcp load balancer
    targetPort: 27017                     #the port on the concerned cluster pods that needs to be attached to service
  clusterIP: None

---

#Deploying mongodb cluster with StatefulSets
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - 0.0.0.0
            - "--smallfiles"
            - "--noprealloc"
            - "--enableMajorityReadConcern"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/mongodb
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "mongodb"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 32Gi
